############################################################
#  	Default Logging Configuration File
#
# You can use a different file by specifying a filename
# with the java.util.logging.config.file system property.  
# For example java -Djava.util.logging.config.file=myfile
# or:   -Djava.util.logging.config.file=./config/properties/logging.properties
############################################################

############################################################
#  	Global properties
############################################################

# "handlers" specifies a comma separated list of log Handler 
# classes.  These handlers will be installed during VM startup.
# Note that these classes must be on the system classpath.
# By default we only configure a ConsoleHandler, which will only
# show messages at the INFO and above levels.
#handlers= java.util.logging.ConsoleHandler

# To also add the FileHandler, use the following line instead.
#handlers= java.util.logging.FileHandler, java.util.logging.ConsoleHandler

# Additional handlers can be added to the list
handlers = java.util.logging.FileHandler, java.util.logging.ConsoleHandler, rma.util.logging.StdoutConsoleHandler

# Default global logging level.
# This specifies which kinds of events are logged across
# all loggers.  For any given facility this global level
# can be overriden by a facility specific level
# Note that the ConsoleHandler also has a separate level
# setting to limit messages printed to the console.
.level= INFO

############################################################
# Handler specific properties.
# Describes specific configuration info for Handlers.
############################################################

# Individual handlers filter messages by level.
# Messages at or above this level get output by the handler being configured.
# Setting this level = WARNING causes only WARNING and SEVERE messages to be
# output by this handler. 
java.util.logging.ConsoleHandler.level = WARNING
# Configure ConsoleHandler to use RMA CustomFormatter. 
# The default java.util.logging formatter isn't very pretty.
java.util.logging.ConsoleHandler.formatter = rma.util.logging.CustomFormatter

# ConsoleHandler is hard-coded to send log messages to System.err.
# In the Eclipse Console view messages from System.err get colored red, regardless
# of what logging level the log message was.
# GrepConsole plugin could be used to beautify the Eclipse console, but another 
# option is to configure an additional Handler.
# The StdoutConsoleHandler is hard coded to use System.out.
rma.util.logging.StdoutConsoleHandler.formatter = rma.util.logging.CustomFormatter
rma.util.logging.StdoutConsoleHandler.level = ALL
rma.util.logging.StdoutConsoleHandler.filter = rma.util.logging.LevelCeilingFilter

# The following special tokens can be used in the FileHandler pattern property
# which specifies the location and name of the log file.
#   / - standard path separator
#   %t - system temporary directory
#   %h - value of the user.home system property
#   %g - generation number for rotating logs
#   %u - unique number to avoid conflicts
# FileHandler writes to %h/demo0.log by default.
java.util.logging.FileHandler.pattern = %t/cavi_util_logging_%g.log
java.util.logging.FileHandler.level = ALL
java.util.logging.FileHandler.formatter = rma.util.logging.CustomFormatter

############################################################
# Facility specific properties.
# Provides extra control for each logger.
############################################################

# Specify logging levels for specific namespaces.
com.ociweb.level = FINEST

com.rma.level = FINEST
hec.lang.annotation.level = FINER
hec2.level = FINEST
hec.level = FINEST
org.jboss.serial.level = INFO
