# key=name,size,image path,selected image path,width,height
TimeSeries0=TimeSeries,0,Images/modelup.gif,Images/modelsel.gif,14,14
TimeSeries1=TimeSeries,1,Images/modelup.gif,Images/modelsel.gif,20,20
TimeSeries2=TimeSeries,2,Images/modelup.gif,Images/modelsel.gif,40,40
JunctionA0=JunctionA,0,Images/rss/junctionup.gif,Images/junctionsel.gif,14,14
JunctionA1=JunctionA,1,Images/rss/junctionup.gif,Images/junctionsel.gif,20,20
JunctionA2=JunctionA,2,Images/rss/junctionup.gif,Images/junctionsel.gif,40,40
Reservoir0=Reservoir,0,Images/rss/reservoirup.gif,Images/rss/reservoirdown.gif,14,14
Reservoir1=Reservoir,1,Images/rss/reservoirup.gif,Images/rss/reservoirdown.gif,20,20
Reservoir2=Reservoir,2,Images/rss/reservoirup.gif,Images/rss/reservoirdown.gif,40,40
JunctionB0=JunctionB,0,Images/TSicons/junction.gif,Images/TSicons/junctionsel.gif,14,14
JunctionB1=JunctionB,1,Images/TSicons/junction.gif,Images/TSicons/junctionsel.gif,20,20
JunctionB2=JunctionB,2,Images/TSicons/junction.gif,Images/TSicons/junctionsel.gif,40,40
Subbasin0=Subbasin,0,Images/TSicons/subbasin.gif,Images/TSicons/subbasinsel.gif,14,14
Subbasin1=Subbasin,1,Images/TSicons/subbasin.gif,Images/TSicons/subbasinsel.gif,20,20
Subbasin2=Subbasin,2,Images/TSicons/subbasin.gif,Images/TSicons/subbasinsel.gif,40,40
Source0=Source,0,Images/TSicons/source.gif,Images/TSicons/sourcesel.gif,14,14
Source1=Source,1,Images/TSicons/source.gif,Images/TSicons/sourcesel.gif,20,20
Source2=Source,2,Images/TSicons/source.gif,Images/TSicons/sourcesel.gif,40,40
Sink0=Sink,0,Images/TSicons/sink.gif,Images/TSicons/sinksel.gif,14,14
Sink1=Sink,1,Images/TSicons/sink.gif,Images/TSicons/sinksel.gif,20,20
Sink2=Sink,2,Images/TSicons/sink.gif,Images/TSicons/sinksel.gif,40,40
Diversion0=Diversion,0,Images/TSicons/diversion.gif,Images/TSicons/diversionsel.gif,14,14
Diversion1=Diversion,1,Images/TSicons/diversion.gif,Images/TSicons/diversionsel.gif,20,20
Diversion2=Diversion,2,Images/TSicons/diversion.gif,Images/TSicons/diversionsel.gif,40,40
ThumbnailPlot0=ThumbnailPlot,0, , ,30,30
ThumbnailPlot1=ThumbnailPlot,1, , ,45,45
ThumbnailPlot2=ThumbnailPlot,2, , ,60,60
ThresholdColorBar0=ThresholdColorBar,0, , ,60,7
ThresholdColorBar1=ThresholdColorBar,1, , ,100,10
ThresholdColorBar2=ThresholdColorBar,2, , ,140,12
QualityColorBar0=QualityColorBar,0, , ,60,7
QualityColorBar1=QualityColorBar,1, , ,100,10
QualityColorBar2=QualityColorBar,2, , ,140,12


