//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 11:19:12 AM PDT 
//


package usace.rowcps.headless.sigstages.retrieve.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}disclaimers"/>
 *         &lt;element ref="{}sigstages"/>
 *         &lt;element ref="{}sigflows"/>
 *         &lt;element ref="{}zerodatum"/>
 *         &lt;element ref="{}rating"/>
 *         &lt;element ref="{}alt_rating"/>
 *         &lt;element ref="{}observed"/>
 *         &lt;element ref="{}forecast"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="timezone" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="generationtime" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "disclaimers",
    "sigstages",
    "sigflows",
    "zerodatum",
    "rating",
    "altRating",
    "observed",
    "forecast"
})
@XmlRootElement(name = "site")
public class Site {

    @XmlElement(required = true)
    protected Disclaimers disclaimers;
    @XmlElement(required = true)
    protected Sigstages sigstages = null;
    @XmlElement(required = true)
    protected Sigflows sigflows;
    @XmlElement(required = true)
    protected Zerodatum zerodatum;
    @XmlElement(required = true)
    protected Rating rating;
    @XmlElement(name = "alt_rating", required = true)
    protected AltRating altRating;
    @XmlElement(required = true)
    protected Observed observed;
    @XmlElement(required = true)
    protected Forecast forecast;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;
    @XmlAttribute(name = "name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "timezone", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String timezone;
    @XmlAttribute(name = "generationtime", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String generationtime = "";

    /**
     * Gets the value of the disclaimers property.
     * 
     * @return
     *     possible object is
     *     {@link Disclaimers }
     *     
     */
    public Disclaimers getDisclaimers() {
        return disclaimers;
    }

    /**
     * Sets the value of the disclaimers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Disclaimers }
     *     
     */
    public void setDisclaimers(Disclaimers value) {
        this.disclaimers = value;
    }

    /**
     * Gets the value of the sigstages property.
     * 
     * @return
     *     possible object is
     *     {@link Sigstages }
     *     
     */
    public Sigstages getSigstages() {
        return sigstages;
    }

    /**
     * Sets the value of the sigstages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sigstages }
     *     
     */
    public void setSigstages(Sigstages value) {
        this.sigstages = value;
    }

    /**
     * Gets the value of the sigflows property.
     * 
     * @return
     *     possible object is
     *     {@link Sigflows }
     *     
     */
    public Sigflows getSigflows() {
        return sigflows;
    }

    /**
     * Sets the value of the sigflows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sigflows }
     *     
     */
    public void setSigflows(Sigflows value) {
        this.sigflows = value;
    }

    /**
     * Gets the value of the zerodatum property.
     * 
     * @return
     *     possible object is
     *     {@link Zerodatum }
     *     
     */
    public Zerodatum getZerodatum() {
        return zerodatum;
    }

    /**
     * Sets the value of the zerodatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zerodatum }
     *     
     */
    public void setZerodatum(Zerodatum value) {
        this.zerodatum = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link Rating }
     *     
     */
    public Rating getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rating }
     *     
     */
    public void setRating(Rating value) {
        this.rating = value;
    }

    /**
     * Gets the value of the altRating property.
     * 
     * @return
     *     possible object is
     *     {@link AltRating }
     *     
     */
    public AltRating getAltRating() {
        return altRating;
    }

    /**
     * Sets the value of the altRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltRating }
     *     
     */
    public void setAltRating(AltRating value) {
        this.altRating = value;
    }

    /**
     * Gets the value of the observed property.
     * 
     * @return
     *     possible object is
     *     {@link Observed }
     *     
     */
    public Observed getObserved() {
        return observed;
    }

    /**
     * Sets the value of the observed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Observed }
     *     
     */
    public void setObserved(Observed value) {
        this.observed = value;
    }

    /**
     * Gets the value of the forecast property.
     * 
     * @return
     *     possible object is
     *     {@link Forecast }
     *     
     */
    public Forecast getForecast() {
        return forecast;
    }

    /**
     * Sets the value of the forecast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Forecast }
     *     
     */
    public void setForecast(Forecast value) {
        this.forecast = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }
    
    /**
     * Gets the value of the generationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationtime(){
        return generationtime;
    }
    
    /**
     * Sets the value of the generationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationtime(String value){
        this.generationtime = value;
    }
}
