//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 11:19:12 AM PDT 
//


package usace.rowcps.headless.sigstages.retrieve.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}valid"/>
 *         &lt;element ref="{}primary"/>
 *         &lt;element ref="{}secondary"/>
 *         &lt;element ref="{}pedts"/>
 *       &lt;/sequence>
 *       &lt;attribute name="flow" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="flowUnits" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="stage" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="stageUnits" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valid",
    "primary",
    "secondary",
    "pedts"
})
@XmlRootElement(name = "datum")
public class Datum {

    protected Valid valid;
    protected Primary primary;
    protected Secondary secondary;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pedts;
    @XmlAttribute(name = "flow")
    protected Float flow;
    @XmlAttribute(name = "flowUnits")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String flowUnits;
    @XmlAttribute(name = "stage")
    protected Float stage;
    @XmlAttribute(name = "stageUnits")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String stageUnits;

    /**
     * Gets the value of the valid property.
     * 
     * @return
     *     possible object is
     *     {@link Valid }
     *     
     */
    public Valid getValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Valid }
     *     
     */
    public void setValid(Valid value) {
        this.valid = value;
    }

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link Primary }
     *     
     */
    public Primary getPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Primary }
     *     
     */
    public void setPrimary(Primary value) {
        this.primary = value;
    }

    /**
     * Gets the value of the secondary property.
     * 
     * @return
     *     possible object is
     *     {@link Secondary }
     *     
     */
    public Secondary getSecondary() {
        return secondary;
    }

    /**
     * Sets the value of the secondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Secondary }
     *     
     */
    public void setSecondary(Secondary value) {
        this.secondary = value;
    }

    /**
     * Gets the value of the pedts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPedts() {
        return pedts;
    }

    /**
     * Sets the value of the pedts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPedts(String value) {
        this.pedts = value;
    }

    /**
     * Gets the value of the flow property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFlow() {
        return flow;
    }

    /**
     * Sets the value of the flow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFlow(Float value) {
        this.flow = value;
    }

    /**
     * Gets the value of the flowUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowUnits() {
        return flowUnits;
    }

    /**
     * Sets the value of the flowUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowUnits(String value) {
        this.flowUnits = value;
    }

    /**
     * Gets the value of the stage property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getStage() {
        return stage;
    }

    /**
     * Sets the value of the stage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setStage(Float value) {
        this.stage = value;
    }

    /**
     * Gets the value of the stageUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStageUnits() {
        return stageUnits;
    }

    /**
     * Sets the value of the stageUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStageUnits(String value) {
        this.stageUnits = value;
    }

}
