//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 11:19:12 AM PDT 
//


package usace.rowcps.headless.sigstages.retrieve.xmlmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the usace.rowcps.headless.sigstages.xmlmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Pedts_QNAME = new QName("", "pedts");
    private final static QName _AHPSXMLversion_QNAME = new QName("", "AHPSXMLversion");
    private final static QName _Status_QNAME = new QName("", "status");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: usace.rowcps.headless.sigstages.xmlmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Datum }
     * 
     */
    public Datum createDatum() {
        return new Datum();
    }

    /**
     * Create an instance of {@link Valid }
     * 
     */
    public Valid createValid() {
        return new Valid();
    }

    /**
     * Create an instance of {@link Primary }
     * 
     */
    public Primary createPrimary() {
        return new Primary();
    }

    /**
     * Create an instance of {@link Secondary }
     * 
     */
    public Secondary createSecondary() {
        return new Secondary();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link Sigstages }
     * 
     */
    public Sigstages createSigstages() {
        return new Sigstages();
    }

    /**
     * Create an instance of {@link Low }
     * 
     */
    public Low createLow() {
        return new Low();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Bankfull }
     * 
     */
    public Bankfull createBankfull() {
        return new Bankfull();
    }

    /**
     * Create an instance of {@link Flood }
     * 
     */
    public Flood createFlood() {
        return new Flood();
    }

    /**
     * Create an instance of {@link Moderate }
     * 
     */
    public Moderate createModerate() {
        return new Moderate();
    }

    /**
     * Create an instance of {@link Major }
     * 
     */
    public Major createMajor() {
        return new Major();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link Observed }
     * 
     */
    public Observed createObserved() {
        return new Observed();
    }

    /**
     * Create an instance of {@link Disclaimers }
     * 
     */
    public Disclaimers createDisclaimers() {
        return new Disclaimers();
    }

    /**
     * Create an instance of {@link Quality }
     * 
     */
    public Quality createQuality() {
        return new Quality();
    }

    /**
     * Create an instance of {@link Standing }
     * 
     */
    public Standing createStanding() {
        return new Standing();
    }

    /**
     * Create an instance of {@link Zerodatum }
     * 
     */
    public Zerodatum createZerodatum() {
        return new Zerodatum();
    }

    /**
     * Create an instance of {@link Forecast }
     * 
     */
    public Forecast createForecast() {
        return new Forecast();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link Sigflows }
     * 
     */
    public Sigflows createSigflows() {
        return new Sigflows();
    }

    /**
     * Create an instance of {@link AltRating }
     * 
     */
    public AltRating createAltRating() {
        return new AltRating();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pedts")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPedts(String value) {
        return new JAXBElement<String>(_Pedts_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AHPSXMLversion")
    public JAXBElement<Float> createAHPSXMLversion(Float value) {
        return new JAXBElement<Float>(_AHPSXMLversion_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

}
