//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 11:19:12 AM PDT 
//


package usace.rowcps.headless.sigstages.retrieve.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}low"/>
 *         &lt;element ref="{}action"/>
 *         &lt;element ref="{}bankfull"/>
 *         &lt;element ref="{}flood"/>
 *         &lt;element ref="{}moderate"/>
 *         &lt;element ref="{}major"/>
 *         &lt;element ref="{}record"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "low",
    "action",
    "bankfull",
    "flood",
    "moderate",
    "major",
    "record"
})
@XmlRootElement(name = "sigstages")
public class Sigstages {

    @XmlElement(required = true)
    protected Low low = null;
    @XmlElement(required = true)
    protected Action action = null;
    @XmlElement(required = true)
    protected Bankfull bankfull = null;
    @XmlElement(required = true)
    protected Flood flood = null;
    @XmlElement(required = true)
    protected Moderate moderate = null;
    @XmlElement(required = true)
    protected Major major = null;
    @XmlElement(required = true)
    protected Record record = null;

    /**
     * Gets the value of the low property.
     * 
     * @return
     *     possible object is
     *     {@link Low }
     *     
     */
    public Low getLow() {
        return low;
    }

    /**
     * Sets the value of the low property.
     * 
     * @param value
     *     allowed object is
     *     {@link Low }
     *     
     */
    public void setLow(Low value) {
        this.low = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link Action }
     *     
     */
    public Action getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action }
     *     
     */
    public void setAction(Action value) {
        this.action = value;
    }

    /**
     * Gets the value of the bankfull property.
     * 
     * @return
     *     possible object is
     *     {@link Bankfull }
     *     
     */
    public Bankfull getBankfull() {
        return bankfull;
    }

    /**
     * Sets the value of the bankfull property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bankfull }
     *     
     */
    public void setBankfull(Bankfull value) {
        this.bankfull = value;
    }

    /**
     * Gets the value of the flood property.
     * 
     * @return
     *     possible object is
     *     {@link Flood }
     *     
     */
    public Flood getFlood() {
        return flood;
    }

    /**
     * Sets the value of the flood property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flood }
     *     
     */
    public void setFlood(Flood value) {
        this.flood = value;
    }

    /**
     * Gets the value of the moderate property.
     * 
     * @return
     *     possible object is
     *     {@link Moderate }
     *     
     */
    public Moderate getModerate() {
        return moderate;
    }

    /**
     * Sets the value of the moderate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Moderate }
     *     
     */
    public void setModerate(Moderate value) {
        this.moderate = value;
    }

    /**
     * Gets the value of the major property.
     * 
     * @return
     *     possible object is
     *     {@link Major }
     *     
     */
    public Major getMajor() {
        return major;
    }

    /**
     * Sets the value of the major property.
     * 
     * @param value
     *     allowed object is
     *     {@link Major }
     *     
     */
    public void setMajor(Major value) {
        this.major = value;
    }

    /**
     * Gets the value of the record property.
     * 
     * @return
     *     possible object is
     *     {@link Record }
     *     
     */
    public Record getRecord() {
        return record;
    }

    /**
     * Sets the value of the record property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record }
     *     
     */
    public void setRecord(Record value) {
        this.record = value;
    }

}
